### PR TITLE
Configure linter, fix linter issues (#55)

### LINKED ISSUE #55: Fix linter issues

### PR DESCRIPTION
**Pull request by alexeyinkin**
Resolves #55

### CODE REVIEW

**Comment by alexeyinkin** [comment]
Resolves #55

File: lib/src/line_numbers/line_number_controller.dart [hunk 1]
```diff
@@ -13,8 +13,8 @@ class LineNumberController extends TextEditingController {
     TextStyle? style,
     bool? withComposing,
   }) {
-    final children = <TextSpan>[];
-    final list = text.split("\n");
+    final children = <InlineSpan>[];
```
Comment (alexeyinkin) [inline lib/src/line_numbers/line_number_controller.dart:16]: I am experimenting with adding other spans here locally. This simplifies merges to me.
